- src/Data/Parameterized/TH/GADT.hs
@robdockins @brianhuffman @joehendrix 
After our discussion on Friday about how to implement `compareF` in a way that reduces build times I've come up with this change. I'll test this change against crucible when I get to work tomorrow.
Here's an example of the new generated code:
```haskell
data ExampleType a where
Int :: ExampleType Int
Bool :: ExampleType Bool
Char :: ExampleType Bool
Wrap :: ExampleType a -> ExampleType a -> ExampleType a
instance OrdF ExampleType where
compareF = $(structuralTypeOrd [t| ExampleType |] [(AnyType, [| compareF |])])
```
```haskell
MyTest.hs:(21,16)-(22,57): Splicing expression
structuralTypeOrd [t| ExampleType |] [(AnyType, [| compareF |])]
======>
\ x y
-> let
yn :: Int
yn
= case y of {
Int {} -> 0
Bool {} -> 1
Char {} -> 2
Wrap {} -> 3 }
in
case x of …
```
> Reimplement structuralTypeOrd in order to avoid coverage checker issues

- src/Data/Parameterized/NatRepr.hs
```haskell
withKnownNat :: forall n r. NatRepr n -> (KnownNat n => r) -> r
```
> Add withKnownNat

- parameterized-utils.cabal
- src/Data/Parameterized/Map.hs
This also bumps the minor version number for dependencies.
> Additional folds and map for parameterized map.

- src/Data/Parameterized/Context/Safe.hs
- src/Data/Parameterized/Context/Unsafe.hs
I need to be able to go from a `Diff l r` to a context `app` such that `r = l <+> app`, and there is no way to do this without adding it directly to the modules that define `Diff`. Let me know if you have any questions... Thanks!
> Emw4 is append

- src/Data/Parameterized/Context/Safe.hs
- src/Data/Parameterized/Context/Unsafe.hs
- src/Data/Parameterized/Map.hs
- src/Data/Parameterized/Peano.hs
- src/Data/Parameterized/SymbolRepr.hs
Just waiting for CI before merging
> Remove unused LANGUAGE pragmas (using hlint)

- src/Data/Parameterized/NatRepr.hs
@kquick It would be nice to get this into the hackage release if it is kosher.
> NatRepr: added Data.Data instance, removed unused Data.Proxy import

- parameterized-utils.cabal
- src/Data/Parameterized/TH/GADT.hs
> Adapt to version 0.3 of th-abstraction package.

- src/Data/Parameterized/TH/GADT.hs
> Off-by-one error in TH code generator

- src/Data/Parameterized/Map.hs
> Document D.P.Map.union/mergeWithKeyM

- src/Data/Parameterized/TH/GADT.hs
> Make asTypeCon type more specific

- src/Data/Parameterized/Some.hs
Adds instances of FunctorF, FoldableF, and TraversableF for Some
> Add instances for Some

- src/Data/Parameterized/Context/Safe.hs
- src/Data/Parameterized/Context/Unsafe.hs
This allows us to deconstruct indexes in a typed way
> Implement IndexView

- .gitignore
- src/Data/Parameterized/Context/Safe.hs
- src/Data/Parameterized/Context/Unsafe.hs
> Add addDiff operation

- src/Data/Parameterized/NatRepr.hs
I'm not sure why this function isn't here already, but I needed it, so it seems like a good thing to add.
> add plusAssoc for reassociating addition

- src/Data/Parameterized/NatRepr.hs
Fixes #74, which notes two haddock errors that Brian found
> Fix two haddock errors

- parameterized-utils.cabal
Builds fine and all tests pass here.
> Allow tasty 1.3

- parameterized-utils.cabal
Builds fine and all tests pass here.
> Allow th-abstraction 0.4

- src/Data/Parameterized/Classes.hs
This adds documentation requested in issue #63.
> Documentation and refined minimal operations for OrdF

- src/Data/Parameterized/Classes.hs
@robdockins Do these seem reasonable?
> Adds some instances for Proxy.

- Changelog.md
- parameterized-utils.cabal
- src/Data/Parameterized/Axiom.hs
- src/Data/Parameterized/Context/Unsafe.hs
- src/Data/Parameterized/Ctx/Proofs.hs
- src/Data/Parameterized/NatRepr.hs
- src/Data/Parameterized/NatRepr/Internal.hs
- src/Data/Parameterized/Nonce.hs
- src/Data/Parameterized/Nonce/Unsafe.hs
- src/Data/Parameterized/Peano.hs
- src/Data/Parameterized/SymbolRepr.hs
> Factor out `unsafeCoerce Refl` into its own definition

- parameterized-utils.cabal
Builds fine and all tests pass.
> Allow vector 0.13

- parameterized-utils.cabal
Builds fine and all tests pass.
> Allow lens 5.2

- Changelog.md
- parameterized-utils.cabal
Once this lands, I will make a new Hackage release.
> Preparations for `2.1.8.0` release

- parameterized-utils.cabal
> Allow building with `th-abstraction-0.7.*`

- parameterized-utils.cabal
> Allow building with `hashtables-1.4.*`

- doc/dev.md
By keeping track of this list, we can hopefully ensure that no important concerns get overlooked during the development process.
I'm sure there are projects that I'm not currently aware of that should be added to this list, please chime in with an entry for them!
> doc: List some downstream projects in dev docs

- .github/workflows/doc.yml
- .github/workflows/test.yml
- doc/dev.md
- parameterized-utils.cabal
> Support GHC 9.12
