GaloisInc/parameterized-utils

src/Data/Parameterized/Classes.hs, src/Data/Parameterized/Context/Safe.hs, src/Data/Parameterized/Context/Unsafe.hs, src/Data/Parameterized/NatRepr.hs, src/Data/Parameterized/SymbolRepr.hs
This is directly pulled out of 'Lang.Crucible.BaseTypes', but it's useful in situations outside of Crucible, too.
=> Add 'KnownRepr', a class for generating singleton type values

src/Data/Parameterized/Classes.hs, src/Data/Parameterized/List.hs
By adding `showsPrecF`, analogous to `showsPrec` in `Show`.
Also, update the `Show` manual instance for `Data.Parameterized.List`
to insert parens when neded, by using `showsPrec` and `showsPrecF`
instead of `show`. E.g. in Brittle
SynthInstruction RealOpcode AddRr R32 Reg1 :< R32 Reg3 :< Nil
becomes
SynthInstruction (RealOpcode AddRr) (R32 Reg1 :< (R32 Reg3 :< Nil))
after using `showsPrecF` in place of `showF` in the manual `Show`
instance for `SynthInstruction`.
=> Add precedence support to ShowF

parameterized-utils.cabal, src/Data/Parameterized/DecidableEq.hs, src/Data/Parameterized/NatRepr.hs, src/Data/Parameterized/Vector.hs, test/Test/Vector.hs
I implemented several things that I didn't end up needing.
In this PR:
- `NatRepr`:
+ Variants of `natRec`
+ Facts about `<`
+ Decidable relations: `=` and `<=`
- `Vector`:
+ Functions for creating vectors: `cons`, `snoc`, `generate`, `generateM`
+ `splitWithM`
=> Construction and monadic splitting of vectors

parameterized-utils.cabal, src/Data/Parameterized/NatRepr.hs, src/Data/Parameterized/Nonce.hs, src/Data/Parameterized/Vector.hs, test/Test/Vector.hs
This commit should get everything ready for GHC 8.6.1.
There are warnings when building the testsuite, but this seems unchanged from building on 8.4.3, so I did not try to fix.
=> Update for GHC 8.6.1

src/Data/Parameterized/TraversableF.hs
Improvement on #20, we don't need full `Traversable*` instances
=> FunctorF instance for Compose of a FunctorF with a FunctorFC

parameterized-utils.cabal, src/Data/Parameterized/NatRepr.hs, src/Data/Parameterized/Peano.hs
Peano-based version of natural numbers.  GHC.TypeLits.Nat is great for reasoning about natural number arithmetic.  However, the type system cannot use it to reason about recursively defined type-level functions over naturals. Instead, a more traditional implementation is needed.
=> Peano natural numbers

parameterized-utils.cabal, src/Data/Parameterized/Classes.hs, src/Data/Parameterized/ClassesC.hs, src/Data/Parameterized/Compose.hs
All of this is helpful in my current task of adding a new type family to Crucible with kind `:: (BaseType -> Type) -> Type`.
=> New modules: ClassesC and Compose

parameterized-utils.cabal, src/Data/Parameterized/Peano.hs, src/Data/Parameterized/WithRepr.hs
This PR makes two changes:
- Adds CPP to the Peano module so that it can be compiled without using unsafeCoerce 
(not recommended)
- Adds a new "WithRepr" class that generalizes "withPeanoRepr" and "withKnownNat" 
(and provides additional instances for Symbol, Assignment and List).
=> WithRepr & Safe Peano

parameterized-utils.cabal, src/Data/Parameterized/BoolRepr.hs, src/Data/Parameterized/Peano.hs, src/Data/Parameterized/WithRepr.hs
I needed runtime versions of < etc for Peano, so I added a BoolRepr module for runtime booleans.
=> BoolRepr + Peano comparisons

parameterized-utils.cabal
=> Relax lens version bounds

src/Data/Parameterized/TraversableF.hs, src/Data/Parameterized/TraversableFC.hs
It's customary to have for as a flipped traverse. This adds the
functions to TraversableF and TraversableFC. It also exposes
forF_ which was previously named forMF_ but wasn't actually
exported. I've updated the name to match current practices
while exporting it.
I've deprecated the older forMFC_ name as the forM name
typically indicates a legacy Monad constraint.
=> for functions for TraversableF[C]

src/Data/Parameterized/TH/GADT.hs
Function application test happens at 11 and not 10 in GHC derived Show instances, this change makes parameterized-utils compatible with derived instances.
=> Fix precedences in structuralShowsPrec

parameterized-utils.cabal, src/Data/Parameterized/All.hs
This is useful e.g. when defining instances for only polymorphic instances of an indexed datatype. 
For a concrete example of how I'd use this in SAW, I'd like to add `IsValue`/`FromValue` instances to `Any CrucibleSetupValue`, i.e. only those `SetupValue`s that are polymorphic in the LLVM architecture.
=> New module: All

src/Data/Parameterized/Context.hs
I know it's easy to get from `traverseAndCollect`, but it might make sense to include this.
=> traverseWithIndex_ for mapping functions returning ().

src/Data/Parameterized/Context.hs
into a prefix and all remaining arguments, provided the
assignment begins with the given prefix value.
=> Add the `splitPrefix` operation, which splits an assignment

parameterized-utils.cabal, src/Data/Parameterized/Compose.hs, stack-8.4.yaml, stack-8.6.yaml
GHC 8.10 will introduce a `TestEquality` instance for `Compose`, which clashes with the one that `parameterized-utils` currently defines in `Data.Parameterized.Compose` as an orphan instance. To achieve forward compatibility with 8.10, this patch removes `parameterized-utils`' orphan instance and replaces it with the one in `base-orphans`, the canonical home for orphan instances for types in the `base` library. (Note that on 8.10 or later, this will simply use the instance found in `base`—the orphan instance is only used on older GHCs for backwards compatibility.)
=> Use base-orphans to provide TestEquality instance for Compose

src/Data/Parameterized/HashTable.hs
...rather than Cuckoo.
This is needed because the "Cuckoo" implementation in `hashtables` appears to be buggy and not well-supported.
=> hashtable-linear: changes hashtable implementation to use Linear

src/Data/Parameterized/Classes.hs, src/Data/Parameterized/Compose.hs, src/Data/Parameterized/Context.hs, src/Data/Parameterized/Context/Safe.hs, src/Data/Parameterized/Context/Unsafe.hs, src/Data/Parameterized/Map.hs, src/Data/Parameterized/Nonce/Transformers.hs, src/Data/Parameterized/TH/GADT.hs
GHC 8.10 is more strict about kind variables in explicitly-quantified signatures.  Also squash some warnings.
=> GHC 8.10 updates

src/Data/Parameterized/Context.hs, src/Data/Parameterized/Context/Safe.hs, src/Data/Parameterized/Context/Unsafe.hs, test/Test/Context.hs
Adds equivalent Context operations that are now defined over the suffix of a Context-append, rather than the prefix.
=> add functions to support left-appended Contexts

src/Data/Parameterized/Nonce.hs
Just some minor typos.
Arguably, "in the 'ST' monad" and "in the 'IO' monad" are fairly redundant.
=> Documentation fixes

src/Data/Parameterized/Classes.hs, src/Data/Parameterized/Context.hs, src/Data/Parameterized/Context/Safe.hs, src/Data/Parameterized/Context/Unsafe.hs, src/Data/Parameterized/Map.hs, src/Data/Parameterized/NatRepr.hs, src/Data/Parameterized/Nonce.hs, src/Data/Parameterized/Peano.hs
Since `parameterized-utils` only supports GHC 8.2 or later, many uses of `MIN_VERSION_base` in the code aren't needed. This patch removes them, alphabetizing language extensions and imports as necessary.
=> Remove unnecessary CPP

src/Data/Parameterized/Context/Safe.hs
The `error` case of `idxlookup` claims to be impossible, but in practice, it is actually reachable:
```
λ> idxlookup id AssignmentEmpty undefined
*** Exception: Data.Parameterized.Context.Safe.lookup: impossible case
CallStack (from HasCallStack):
error, called at src/Data/Parameterized/Context/Safe.hs:505:33 in parameterized-utils-2.1.1.0.99-inplace:Data.Parameterized.Context.Safe
```
We can at least avoid this `impossible case` error message by using `EmptyCase`, which this patch accomplishes.
=> Avoid a use of `error` with EmptyCase

src/Data/Parameterized/Context/Safe.hs, src/Data/Parameterized/Context/Unsafe.hs
Lifting an index from a context to an index into the append of that
context to some other context is a bit cumbersome.  This commit adds
this as utility functions leftIndex and rightIndex.
=> add leftIndex and rightIndex to adjust indices

src/Data/Parameterized/Context.hs, src/Data/Parameterized/Ctx.hs
For some purposes, it is useful to forget the nested structure of a
context of contexts, flattening it into one large context.  This
commit introduces a type family CtxFlatten to capture this at the
type level.
At the value level, the relevant operation consists in flattening
an assignment of assignments over this context of contexts, into
a flat assignment.
=> add CtxFlatten type family and flattenAssignment

src/Data/Parameterized/Classes.hs
When the two sides have the same `k tp`, I think we want `compareF` to respect
`Ord` in all cases.
=> Fixes (I think) a slight error in the laws for OrdF

parameterized-utils.cabal, src/Data/Parameterized/TH/GADT.hs, test/Test/TH.hs, test/UnitTest.hs
`mkRepr` generates runtime repr types for a given data kind (just like the singletons library). `mkKnownRepr `generates `KnownRepr` instances for data kinds.
=> Adds TH primitives for generating reprs

.github/workflows/test.yml
Previously, tests were sometimes not included by Cabal in its build plan, leading to spurrious CI failures.
Fixes #118.
=> CI: Add configuration step that adds tests to Cabal build plan

parameterized-utils.cabal, src/Data/Parameterized/Context/Safe.hs, src/Data/Parameterized/Context/Unsafe.hs, src/Data/Parameterized/List.hs, src/Data/Parameterized/TraversableFC/WithIndex.hs, test/Test/Context.hs
Add indexed functors, folds, and traversals inspired by the indexed-traversable
(which is where the naming scheme comes from) and lens packages.
The current contents of the List and Assignment modules provide additional
motivation: List already implements and exports a minimal set of methods for
each of the added classes, but Assignment only implemented
'traverseWithIndex' (AKA 'itraverseFC'); this indicates that identifying this
abstraction enables code sharing and increased functionality between these
similar modules/datatypes.
Additionally, Assignment now gets 'ifoldMapFC', 'imapFC' and friends "for free",
because they have default implementations based on 'itraverseFC'.
At some point, it may make sense to implement similar classes for the *F family:
'FunctorF', 'FoldableF', and …
=> TraversableFCWithIndex: Indexed traversals, folds, and maps

src/Data/Parameterized/TraversableFC.hs, test/Test/Context.hs
I realized that the laws and tests I wrote for #117 implicitly relied on the assumption that the other *FC classes had laws and tests for those laws. This isn't all of them, but it's a start.
Also, strengthen a few existing *WithIndex tests.
=> Document FunctorFC laws, test Assignment instance

parameterized-utils.cabal, src/Data/Parameterized/Vector.hs, test/Test/Vector.hs
Also:
- Add iterateNM and iterateN in the style of the vector package, to support the helper methods indicesUpTo and indicesOf.
- Improve test infrastructure by not fixing the sizes of vectors, but instead using genSomeVector
- Add tests of functor laws
=> {Functor,Foldable,Traversable}WithIndex instances for Vector

README.md, parameterized-utils.cabal, src/Data/Parameterized/Fin.hs, src/Data/Parameterized/Vector.hs, test/Test/Fin.hs, test/Test/Vector.hs, test/UnitTest.hs
The type 'VectorIndex' was named something more specific than it needed to be. Another way to look at it is that it's the definition of the family of finite types.
=> Fin: Finite types

.github/workflows/test.yml, Changelog.md, parameterized-utils.cabal, src/Data/Parameterized/Context/Unsafe.hs, src/Data/Parameterized/NatRepr.hs, src/Data/Parameterized/NatRepr/Internal.hs, src/Data/Parameterized/TH/GADT.hs, src/Data/Parameterized/Vector.hs, test/Test/Vector.hs
This contains a variety of changes needed to make `parameterized-utils` compile
with GHC 9.2:
* In `base-4.16.*`, the internals of the `(<=)` type family in `GHC.TypeNats` have changed (see [here](https://gitlab.haskell.org/ghc/ghc/-/wikis/migration/9.2?version_id=7e2ce63ba042c1934654c4316dc02028d8d3dd31#changes-to-the-and-type-families)). As a result, GHC is no longer able to infer `0 <= n` for all `n :: Nat`, as this fact must now be assumed as an axiom. This prevents a handful of functions in `Data.Parameterized.NatRepr` and `Data.Parameterized.Vector` from compiling, as they relied on `0 <= n` to typecheck.
I resolved this issue by introducing a new `leqZero :: LeqProof 0 n` function to `Data.Parameterized.NatRepr` and using it where needed.
* In `template-haskell-2.18.*`, the type of …
=> Support building with GHC 9.2

.github/workflows/test.yml, parameterized-utils.cabal, test/Test/Context.hs, test/Test/NatRepr.hs, test/Test/Vector.hs
`tasty-hedgehog-1.2.0.0` has deprecated the [`testProperty`](https://hackage.haskell.org/package/tasty-hedgehog-1.2.0.0/docs/Test-Tasty-Hedgehog.html#v:testProperty) function in favor of [`testPropertyNamed`](https://hackage.haskell.org/package/tasty-hedgehog-1.2.0.0/docs/Test-Tasty-Hedgehog.html#v:testPropertyNamed), which expects the name of the `Property` value being tested as an argument. To avoid heaps of deprecation warnings when building the test suite, let's switch from `testProperty` to `testPropertyNamed`.
=> Replace `testProperty` with `testPropertyNamed`

.github/workflows/test.yml, parameterized-utils.cabal
`Data.Parameterized.ClassesC` relies on all of its imports being `Safe` or `Trustworthy`, but prior to `th-abstraction-0.4.2.0`, the modules in `th-abstraction` were unsafe. This unsafety can leak up to `parameterized-utils`, causing the build failure observed in #139.
The simplest fix is to require `th-abstraction-0.4.2.0` as the minimum, which this patch accomplishes. That version has been out for nearly two years, so this shouldn't cause any undue complications with downstream dependencies not supporting it.
Fixes #139.
=> Raise lower version bounds on `th-abstraction` to `>=0.4.2`

Changelog.md, parameterized-utils.cabal, src/Data/Parameterized/Classes.hs, src/Data/Parameterized/Context/Safe.hs, src/Data/Parameterized/Context/Unsafe.hs, src/Data/Parameterized/Some.hs
Because `hashable-1.4.0.0` adds an `Eq` superclass to `Hashable`, several `Hashable` instances in `parameterized-utils` now must add additional constraints to satisfy the corresponding `Eq` instances. For instance, several `Eq` instances have `TestEquality` constraints, so the `Hashable` instances must have corresponding `TestEquality` constraints as well.
Fixes #126.
=> Allow building with `hashable-1.4.*`

.github/workflows/test.yml, parameterized-utils.cabal, src/Data/Parameterized/Fin.hs
The only change needed is to enable `UndecidableInstances` in `Data.Parameterized.Fin`, which is necessary due to GHC 9.4 being pickier about undecidable instance checking. See [this section](https://gitlab.haskell.org/ghc/ghc/-/wikis/migration/9.4?version_id=24540b698481cf2b0bd11029b58eaddc0fbfbb31#stricter-undecidableinstances-checking) of the GHC 9.4 Migration Guide.
Fixes #141.
=> Allow building with GHC 9.4

parameterized-utils.cabal, src/Data/Parameterized/ClassesC.hs
For compatibility with lens < 5. Fixes #152.
=> Mark `ClassesC` as Trustworthy

.github/workflows/test.yml, parameterized-utils.cabal, test/Test/SymbolRepr.hs
This is mostly a matter of bumping upper version bounds. I needed to perform some mild refactoring in the test suite to avoid `-Wx-partial` warnings due to uses of the `head` and `tail` functions.
=> Allow building with GHC 9.8

parameterized-utils.cabal
Bump upper version bounds for these packages to allow building with the latest Hackage releases.
Fixes #163.
=> Allow building with `lens-5.3.*` and `hashable-1.5.*`

.github/workflows/test.yml, Changelog.md, parameterized-utils.cabal, src/Data/Parameterized/Map.hs
`base-4.20` (bundled with GHC 9.10) re-exports `foldl'` from the `Prelude`. This causes an `-Wunused-imports` warning when building `Data.Parameterized.Map`, which separately imports `foldl'` from `Data.List`.
This patch makes the `Data.List` import qualified to avoid this issue and make it possible to build the code warning-free on GHC 9.10 and older.
=> Avoid -Wunused-imports warning with `base-4.20` (GHC 9.10)

Changelog.md, parameterized-utils.cabal, src/Data/Parameterized/TraversableF.hs, src/Data/Parameterized/TraversableFC.hs
These aren't motivated by any particular use-case, but in general it's nice to have instances from `base` in case downstream packages need them, because they can only be defined in this package on pain of orphan instances.
The related [barbies](https://hackage.haskell.org/package/barbies-2.1.1.0) package has all of these.
=> Instances for more types from `base`

Changelog.md, src/Data/Parameterized/BoolRepr.hs, src/Data/Parameterized/Context/Safe.hs, src/Data/Parameterized/Context/Unsafe.hs, src/Data/Parameterized/DataKind.hs, src/Data/Parameterized/List.hs, src/Data/Parameterized/NatRepr/Internal.hs, src/Data/Parameterized/Nonce.hs, src/Data/Parameterized/Nonce/Unsafe.hs, src/Data/Parameterized/Peano.hs, src/Data/Parameterized/SymbolRepr.hs
The library defined several `TestEquality` instances that lacked corresponding `EqF` instances. This patch adds these missing `EqF` instances. Where possible, I ensured that only `EqF` constraints are occurred (lest we end up with strange instances like `instance TestEquality f => EqF (T f)`, which are less general than they could be).
This is one step towards a resolution for #129.
=> Add `EqF` instances for parity with `TestEquality`

.github/workflows/test.yml, doc/dev.md, src/Data/Parameterized/ClassesC.hs
To prevent warnings sneaking in without us noticing! Also, switch to a non-deprecated Haskell setup action to get a non-ancient version of Cabal.
I don't feel strongly about this, just thought it would be nice and figured we could do it if we all agreed.
=> ci: Enable `-Werror=compat -Werror=default`

doc/dev.md
Also add instructions on how to add or remove GHC versions. I find this helpful because the steps can be different for different repos (e.g., repos may or may not have a `tested-with` field, Cabal freeze files, Dockerfiles, etc.).
I have no particular commitment to the three-version policy, it's just the de facto standard amongst our projects.
=> doc: Describe GHC version support policy

.github/workflows/test.yml, doc/dev.md
In between full Hackage releases, it would be nice to be able to read haddocks for the latest commit on the default branch. This PR builds the haddocks in CI, and publishes them to GitHub Pages.
In more detail, this PR breaks the `cabal haddock` step out of the testing job into a separate job for the sake of controlling concurrency and permissions, while reusing the cache from the build step to build the haddocks.
I'd be completetly fine with hearing that we don't think that the maintenance is worth it, I mostly wanted to prototype this for use on our repos that we don't publish to Hackage (e.g., Macaw) and just figured I'd make a PR in case others thought this would be useful.
If we did want to merge this, we would want to temporarily disable the `if` stanza that only deploys on the …
=> ci: Publish haddocks to GitHub Pages

.github/workflows/doc.yml, .github/workflows/test.yml
The setup I introduced in #183 was buggy. The `doc` job would fail on non-`master` branches, because it didn't have enough permissions to access the GitHub Pages "environment", even though if it were run it wouldn't attempt to upload to it.
Also, use a separate cache for documentation builds. This is appropriate, as we can and should build with `--disable-documentation` to save space and time in the `test` job, but *not* build with that flag for the docs. This discrepancy causes dependencies to be built differently, hence separate caches.
Return to checking Haddock well-formedness in `test`.
=> ci: Move Haddocks to their own workflow

.github/workflows/test.yml
I was making a composite action for this (#182), but I realized that it could likely be simplified instead, to the point where such an action would be superfluous! I believe it still addresses the original concerns behind this check, but would appreciate confirmation from @kquick.
Added some more documentation along the lines of https://github.com/GaloisInc/.github/pull/13.
=> ci: Simplify, move, and document the Cabal/GHC compatibility check

.github/workflows/test.yml
None of our current CI workflow is in any way specific to parameterized-utils. It is a generic sequence of steps that could apply equally well to any single-package Haskell repo. I have factored it into a "reusable workflow" https://github.com/GaloisInc/.github/pull/16, and changed the workflow in this repo to import (`uses`) it. This mostly serves as a test-case/demonstration of https://github.com/GaloisInc/.github/pull/16, this PR would need to be updated to point to the merged version of that PR before it could be merged.
=> ci: Package workflow into a "reusable workflow"

.github/dependabot.yml
We have previously manually bumped the pinned versions of the actions used in our CI workflows. Let's automate this process using Dependabot. With this configuration, Dependabot will check for updates weekly, and open pull requests for each of them.
Benefits:
- Save maintainer time when updates are push-button
- See benefits from updated dependencies more quickly and reliably
Risks:
- Requires maintainers to review and merge more PRs
- May create noise for updates that aren't push-button and require some manual intervention
I'm not especially invested in this if people don't like it, I think that both the benefits and risks are fairly marginal.
=> ci: Use Dependabot for weekly bumps to pinned GitHub Actions

.github/workflows/test.yml
See upstream `Note [Parallelism]`. We need to do this here because we override the `cabal configure` flags, which now include `--semaphore` in upstream.
=> ci: Pass `--semaphore` to `cabal configure`
